# This file may not be shared/redistributed without permission. Please read copyright notice in the git repo. If this file contains other copyright notices disregard this text.
"""
This project resembles the Inventory-control problem discussed in (Her25, Subsection 5.1.2) but with more complicated rules.
If you are stuck, the inventory-control problem will be a good place to start.

I recommend to use the DP_stochastic function (as we did with the inventory-control example). This means
your main problem is to build appropriate DPModel-classes to represent the different problems.

References:
  [Her25] Tue Herlau. Sequential decision making. (Freely available online), 2025.
"""
from irlc.ex02.dp_model import DPModel
from irlc.ex02.dp import DP_stochastic
import matplotlib.pyplot as plt
from scipy.stats import binom
from irlc import savepdf
import numpy as np
from gymnasium.spaces.discrete import Discrete


def plot_policy(pi, title, pdf):
    """Helper function to plot the policy functions pi, as generated by the DP_stochastic function. This function
    can be used to visualize which actions are taken in which state (y-axis) at which time step (x-axis)."""
    N = len(pi)
    W = max(pi[0].keys())
    A = np.zeros((W, N))
    for i in range(W):
        for j in range(N):
            A[i, j] = pi[j][i]
    plt.imshow(A)
    plt.title(title)
    savepdf(pdf)
    plt.show()

# TODO: 51 lines missing.
# Constants for problem 1
N_DEFAULT = 14
n_s = 20          # overnight max inventory
n_o = 15          # max order
c_o = 1.5         # order cost
s_p = 2.1         # sale price
W_VALS = (0, 3, 6)
W_PROBS = (0.3, 0.6, 0.1)

class KioskEnvironment():
    def __init__(self, N=14):
        self.N = N                                # planning horizon
        self.action_space      = Discrete(n_o+1)     # Possible actions {0, ... , 15}
        self.observation_space = Discrete(n_s+1)     # Possible observations {0, ... , 20}

    def reset(self):
        self.s = 0                               # reset initial state x0=0
        self.k = 0                               # reset time step k=0
        return self.s, {}                        # Return the state we reset to (and an empty dict)

    def step(self, a):
        w = np.random.choice([0,3,6], p=[0.3, 0.6, 0.1])  # Generate random disturbance. w is number of orders/demand from customers. Buying 0, 3 or 6 blasters
        # TODO: 5 lines missing.
        s_next = max(0, min(20, self.s-w+a))      # min of 20, because max inventory in the morning is 20. max of 0, because inventory cannot be negative. Subtract demand (w) and add action (a) to get next state.
        reward = s_p*(min(self.s+a,w)) - c_o*a    # reward is sales price times number of blasters sold, subtracted by cost times number of blasters bought. min secures we are not selling more than we have          
        terminated = self.k == self.N-1
        self.s = s_next
        self.k += 1
        return s_next, reward, terminated, False, {}  # return transition information  
    

class KioskDPModel(DPModel): 
    def __init__(self, N=N_DEFAULT):
        super().__init__(N=N)

    def A(self, x, k): # Action space A_k(x)
        return set(range(n_o+1))

    def S(self, k): # State space S_k
        return set(range(n_s+1))

    def g(self, x, u, w, k): # Cost function g_k(x,u,w)
        return c_o*u - s_p*min(x+u,w) # cost is negative profit, as we want to minimise cost, and thereby maximise profit

    def f(self, x, u, w, k): # Dynamics f_k(x,u,w)
        return max(0, min(n_s, x + u - w))

    def Pw(self, x, u, k): # Distribution over random disturbances 
        # TODO: 1 lines missing.
        return {0:.3, 3:.6, 6:0.1} # noise distribution

    def gN(self, x):
        return 0 


def warmup_states(): 
    # TODO: 1 lines missing.
    return set(range(n_s+1)) # return state space

def warmup_actions(): 
    # TODO: 1 lines missing.
    return set(range(n_o+1)) # return action space

def solve_kiosk_1(): 
    # TODO: 1 lines missing.
    model = KioskDPModel(N=N_DEFAULT)
    J, pi = DP_stochastic(model) # solve the problem using DP_stochastic and return cost and policy
    return J, pi

def solve_kiosk_2(): 
    # TODO: 1 lines missing.
    raise NotImplementedError("Return cost and policy here (same format as DP_stochastic)")


def main():
    # Problem 14
    print("Available states S_0:", warmup_states())
    print("Available actions A_0(x_0):", warmup_actions())

    J, pi = solve_kiosk_1() # Problem 16
    print("Kiosk1: Expected profits: ", -J[0][0], " imperial credits")
    plot_policy(pi, "Kiosk1", "Latex/figures/kiosk1")
    plt.show()

    J, pi = solve_kiosk_2() # Problem 17
    print("Kiosk 2: Expected profits: ", -J[0][0], " imperial credits")
    plot_policy(pi, "Kiosk2", "Latex/figures/kiosk2")
    plt.show()


if __name__ == "__main__":
    main()
